import 'package:collection/collection.dart';
import 'package:flashcards/bloc/osces/update_osce/forms/check_form/check_form.dart';
import 'package:flashcards/domain/models/core/image_data_wrapper.dart';
import 'package:flashcards/domain/models/osce/question/question.dart';
import 'package:flutter/cupertino.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'question_form.freezed.dart';

@freezed
abstract class QuestionForm with _$QuestionForm {
  const factory QuestionForm({
    required String id,

    /// Used to differentiate if the question is loaded from db or is added locally.
    ///
    /// This way you know if you should call update or add method from repository.
    required bool isLocal,
    required TextEditingController controller,
    required List<CheckForm> checkForms,
    required ImageDataWrapper imageData,

    /// Used to check if the form has changed so that you can ignore sending the request if it's not changed
    required Question original,
  }) = _QuestionForm;

  factory QuestionForm.fromQuestion(Question question) {
    return QuestionForm(
      id: question.id,
      // It's false since this .fromQuestion is called from the question from the db.
      isLocal: false,
      controller: TextEditingController(text: question.text),
      checkForms: question.checks.map((c) => CheckForm.fromCheck(c)).toList(),
      imageData: ImageDataWrapper(imageDownloadUrl: question.imageDownloadUrl),
      original: question,
    );
  }

  factory QuestionForm.initial(String questionId) {
    return QuestionForm(
      id: questionId,
      // It's true because you call this when you locally want to add new question.
      isLocal: true,
      controller: TextEditingController(),
      checkForms: [CheckForm.initial()],
      imageData: ImageDataWrapper(),
      original: Question.empty(),
    );
  }
}

extension QuestionFormX on QuestionForm {
  Question toQuestion(int index) => Question(
    id: id,
    text: controller.text,
    checks:
        checkForms
            .mapIndexed((index, checkForm) => checkForm.toCheck(index))
            .toList(),
    index: index,
  );

  /// You give it question and it tells you if it's different from that question.
  ///
  /// Usually the question you give it is the question generated by calling toQuestion method.
  bool isChanged(Question generatedQuestion) =>
      generatedQuestion != original || imageData.isChanged;
}
